name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: company
          MYSQL_USER: dev
          MYSQL_PASSWORD: password
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
      - name: Set Node version to 12
        uses: actions/setup-node@v1
        with:
          version: 12
        
      - uses: actions/setup-node@v1
      - name: Require password to set for identification
        run: mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'password';"
      
      - uses: actions/setup-node@v1
      - name: mysql version
        run: mysql --version
      
      - name: Node version
        run: node --version
      
      - name: Install NPM  
        run: npm install
      
      - name: Database Connection
        run: node app.js 
