name: Node.js Example
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    # ... some other config ...

    steps:
    - uses: actions/checkout@v1
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3800 
    	container port: 3307 
	    mysql database: 'company'
	    mysql root password: ${{ secrets.RootPassword }}
	    mysql user: 'root' 
	    mysql password: ${{ secrets.DatabasePassword }} # Required if "mysql user" exists. The password for the "mysql user"

    - name: npm install, build, and company
      run: npm install

    - name: check login to mysql
      run: mysql -h 127.0.0.1 -u root -ppassword, exit

    - name: Database Connection
      run: node app.js