name: CI

on:
  push:
    branches: 
      - master
      - staging
  pull_request:
    branches: 
      - master
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
      
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      
        with:
          node-version: ${{ matrix.node-version }}
          
      - uses: actions/checkout@v1
      - run: mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS company;'
      - name: npm initialize       
        run: npm install
      
      - name: Database Connected
        run: node app.js
      
        env: 
         CI: true      
