name: Node.js Example

on:
  pull_request:
  push:
    branches: 
      - master
      - staging 

jobs:
  test-host:
    runs-on: ubuntu-latest
    services:
      mysql: 
    image: mariadb:10.3 
    env:    
        MYSQL_ROOT_PASSWORD: root   
    ports:  
    - 3306:3306 
    options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3