name: Node.js Example

on:
  pull_request:
  push:
    branches: 
      - master
      - staging 

jobs:
  test-host:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 172.18.0.2 --port ${{ job.services.mysql.ports['3306'] }} -utest -ppassword -e "SHOW DATABASES"

  test-container:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Verify MySQL connection from container
        run: |
          apt-get update && apt-get install -y mysql-client
          mysql --host mysql -utest -ppassword -e "SHOW DATABASES"
