name: mysql 2nd method

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: ['10.x']

    steps:
    - uses: actions/checkout@v1
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up MySQL 5.7
      uses: mirromutth/mysql-action@master
      with:
        host port: 3307
        mysql version: 5.7
        mysql database: company
        mysql root password: ${{ secrets.DatabaseRootPassword }}
    - name: npm install, build
      run: |
        npm install
        mysql --version
        node --version
        mysql -h 127.0.0.1 --port 3307 -u root -ppassword -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'password';"
      env:
        CI: true
