name: mysql 2nd method

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: ['10.x']

    steps:
    - uses: actions/checkout@v1
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up MySQL 5.7
      uses: mirromutth/mysql-action@master
      with:
        mysql version: 5.7
        mysql database: company
        mysql root password: ${{ secrets.DatabasePassword }}
    - name: npm install
      run: npm install
    - name: mysql login  
      run: mysql -h 127.0.0.1 -u root -ppassword
      env:
        CI: true
