name: mysql 2nd method

on: 
  push:
   branches:
     - master
 
jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Set up MySQL 5.7
        uses: mirromutth/mysql-action@master
      
        with:
          container port: 3307
          mysql database: 'company'
          mysql root password: ${{ secrets.DatabaseRootPassword }}
          mysql user: 'test'
          mysql password: ${{ secrets.DatabasePassword }}
           
      - name: npm initialize       
        run: npm install
      
      - name: root login
        run: mysql -h 127.0.0.1 --port 3307 -u root -ppassword -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'password';"
      
      - name: Database Connection  
        run: node app.js

      - name: run build
        run: npm run build --if-present  
        env: 
         CI: true
