name: Node.js Example

on: 
  push:
   branches:
     -master
 
jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Set up MySQL 5.7
        uses: mirromutth/mysql-action@master
      
        with:
          container port: 3307
          mysql version: '8.0' 
          mysql database: 'company'
          mysql root password: ${{ secrets.DatabaseRootPassword }}
          mysql user: 'test'
          mysql password: ${{ secrets.DatabasePassword }}
           
      - name: npm initialize       
        run: npm install
        
        env: 
         CI: true